"""
agent.py — LangChain agent setup and execution helpers.

This module uses LangChain's create_agent() API to build a proper agent,
then exposes two public functions:

  1. call_agent(query)   -> invokes the agent and returns the complete text
                            response (used by the HTTP POST /run endpoint).
  2. stream_agent(query) -> async generator that yields text tokens as they
                            are generated by the LLM (used by the WebSocket
                            /ws endpoint for real-time streaming).

How the pieces fit together:
  - create_agent() builds a graph-based agent (powered by LangGraph) with
    an LLM model node and optional tool nodes.
  - The model is specified as "openai:gpt-4o" — LangChain's model identifier
    format that auto-resolves to the correct provider class.
  - OPENAI_API_KEY is read from the environment automatically.
  - For full responses we use agent.ainvoke().
  - For streaming we use agent.astream(stream_mode="messages") which yields
    (token, metadata) tuples with token-level granularity.

Docs:
  - Agents:    https://docs.langchain.com/oss/python/langchain/agents
  - Streaming: https://docs.langchain.com/oss/python/langchain/streaming/overview
"""

from typing import AsyncGenerator

from dotenv import load_dotenv
load_dotenv(override=True)

from langchain.agents import create_agent
from langchain.messages import AIMessageChunk

from tools import ALL_TOOLS

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
MODEL = "openai:gpt-4o"

SYSTEM_PROMPT = (
    "You are a helpful AI assistant with access to file-system and terminal tools. "
    "You can read, write, edit, and delete files, run shell commands, and search "
    "through files using grep. Always confirm destructive actions before executing. "
    "Keep responses clear and concise unless the user asks for detail."
)

# ---------------------------------------------------------------------------
# Build the agent once at module level.
#
# create_agent() returns a compiled LangGraph that wires together:
#   - a model node   (calls the LLM)
#   - a tools node   (executes any registered tools)
#   - edges that loop between them until the model emits a final answer
#
# ALL_TOOLS provides: read_file, write_file, edit_file, delete_file,
#                     run_terminal, grep_search
# ---------------------------------------------------------------------------
agent = create_agent(
    model=MODEL,
    tools=ALL_TOOLS,
    system_prompt=SYSTEM_PROMPT,
)


# ---------------------------------------------------------------------------
# Public API: call_agent  (request-response, used by POST /run)
# ---------------------------------------------------------------------------
async def call_agent(query: str) -> str:
    """
    Send *query* to the agent and return the full text response.

    Uses agent.ainvoke() which runs the full agent graph asynchronously
    and returns the final state (including all messages).

    Args:
        query: The user's question or prompt.

    Returns:
        The agent's complete text reply as a single string.

    Raises:
        RuntimeError: If the agent returns no content.
    """
    # ainvoke() expects a dict with a "messages" key.
    # Each message can be a simple dict with "role" and "content".
    result = await agent.ainvoke(
        {"messages": [{"role": "user", "content": query}]}
    )

    # result["messages"] is the full conversation: user message + AI reply.
    # The last message is the agent's final answer.
    final_message = result["messages"][-1]

    if not final_message.content:
        raise RuntimeError("Agent did not return a response.")

    return final_message.content


# ---------------------------------------------------------------------------
# Public API: stream_agent  (streaming, used by WebSocket /ws)
# ---------------------------------------------------------------------------
async def stream_agent(query: str) -> AsyncGenerator[str, None]:
    """
    Async generator that yields text tokens as the LLM produces them.

    Uses agent.astream() with stream_mode="messages" which yields
    (token, metadata) tuples for every token the LLM generates.
    Each token is an AIMessageChunk whose .content holds a small
    piece of text (typically one word or a few characters).

    Args:
        query: The user's question or prompt.

    Yields:
        Small strings containing partial response text as the LLM
        generates them.
    """
    # stream_mode="messages" gives us token-level streaming.
    # Each yielded item is a (token, metadata) tuple.
    #   - token: a message object (AIMessageChunk for LLM output)
    #   - metadata: dict with info like which node produced this token
    async for token, metadata in agent.astream(
        {"messages": [{"role": "user", "content": query}]},
        stream_mode="messages",
    ):
        # Only yield text from AIMessageChunk objects (skip tool calls,
        # tool results, and other non-text message types).
        if isinstance(token, AIMessageChunk) and token.content:
            yield token.content
